version: '3.8'

services:
  # Banco de Dados PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: group-guru-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: paulo1313
      POSTGRES_DB: whatsapp_saas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Redis (Necessário para filas/cache do WhatsApp)
  redis:
    image: redis:7-alpine
    container_name: group-guru-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: